stages:
  detect_contours:
    cmd: python path/g_test4.py --stage detect_contours
    deps:
    - path/image.npy
    outs:
    - path/outer_contours.npy
    - path/first_level_contours.npy
    - path/filtered_contours_data.pkl

  process_image:
    cmd: python path/g_test4.py --stage process_image
    deps:
    - path/outer_contours.npy
    - path/first_level_contours.npy
    outs:
    - path/contours_with_data.pkl
    - path/shop_data.pkl
    - path/skeleton_contours_with_data.pkl

  skeletonize_image:
    cmd: python path/g_test4.py --stage skeletonize_image
    deps:
    - path/image.npy
    - path/skeleton_contours_with_data.pkl
    outs:
    - path/path_points.npy

  filter_path_points:
    cmd: python path/g_test4.py --stage filter_path_points
    deps:
    - path/path_points.npy
    - path/image.npy
    outs:
    - path/filtered_path_points.npy
    - path/remaining_path_points.npy

  reduce_path_points:
    cmd: python path/g_test4.py --stage reduce_path_points
    deps:
    - path/remaining_path_points.npy
    outs:
    - path/final_path_points.npy

  highlight_and_find_max_distance_center_points:
    cmd: python path/g_test4.py --stage highlight_and_find_max_distance_center_points
    deps:
    - path/contours_with_data.pkl
    - path/remaining_path_points.npy
    outs:
    - path/shop_points.pkl
    - path/detailed_shop_data.pkl
    - path/shop_names.pkl

  save_results:
    cmd: python path/g_test4.py --stage save_results
    deps:
    - path/final_path_points.npy
    - path/detailed_shop_data.pkl
    outs:
    - path/final_path_points.xlsx
    - path/cordshop1.xlsx
    - path/shop_distance_matrix.xlsx
