stages:
  load_image:
    cmd: python path/image.jpg'
    deps:
      - path/image.jpg
    outs:
      - path/processed_image.jpg

  detect_contours:
    cmd: python path/processed_image.jpg'
    deps:
      - path/processed_image.jpg
    outs:
      - path/contours.pkl

  process_image:
    cmd: python path/processed_image.jpg'
    deps:
      - path/processed_image.jpg
    outs:
      - path/contours_with_data.pkl
      - path/shop_data_intermediate.pkl

  skeletonize_image:
    cmd: python 'path/processed_image.jpg', 'path/contours_with_data.pkl'
    deps:
      - path/processed_image.jpg
      - path/contours_with_data.pkl
    outs:
      - path/path_points.pkl

  highlight_and_find_max_distance_center_points:
    cmd: python 'path/contours_with_data.pkl', 'path/path_points.pkl'
    deps:
      - path/contours_with_data.pkl
      - path/path_points.pkl
    outs:
      - path/shop_points.pkl
      - path/shop_data_final.pkl

  filter_end_path_points:
    cmd: python path/path_points.pkl'
    deps:
      - path/path_points.pkl
    outs:
      - path/filtered_path_points.pkl
      - path/remaining_path_points.pkl

  reduce_path_points:
    cmd: python path/remaining_path_points.pkl
    deps:
      - path/remaining_path_points.pkl
    outs:
      - path/final_path_points.pkl

  save_data:
    cmd: python 'path/final_path_points.pkl', 'path/shop_data_final.pkl'
    deps:
      - path/final_path_points.pkl
      - path/shop_data_final.pkl
    outs:
      - path/final_path_points.xlsx
      - path/cordshop.xlsx
      - path/shop_distance_matrix.xlsx
