stages:
  detect_contours:
    cmd: python g_test4.py detect_contours
    deps:
      - path/SHOW.jpg
    outs:
      - path/contours_data.pkl

  process_image:
    cmd: python g_test4.py process_image
    deps:
      - path/contours_data.pkl
    outs:
      - path/contours_with_data.pkl
      - path/shop_data.pkl

  skeletonize_image:
    cmd: python g_test4.py skeletonize_image
    deps:
      - path/contours_with_data.pkl
    outs:
      - path/path_points.npy

  highlight_and_find_max_distance_center_points:
    cmd: python g_test4.py highlight_and_find_max_distance_center_points
    deps:
      - path/path_points.npy
      - path/contours_with_data.pkl
    outs:
      - path/shop_points.pkl
      - path/shop_data_detailed.pkl

  filter_end_path_points:
    cmd: python g_test4.py filter_end_path_points
    deps:
      - path/path_points.npy
    outs:
      - path/filtered_path_points.npy

  reduce_path_points:
    cmd: python g_test4.py reduce_path_points
    deps:
      - path/filtered_path_points.npy
    outs:
      - path/final_path_points.npy

  calculate_shop_distance_matrix:
    cmd: python g_test4.py calculate_shop_distance_matrix
    deps:
      - path/shop_data_detailed.pkl
    outs:
      - path/shop_distance_matrix.xlsx
